# Generated by Django 5.1.1 on 2024-10-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categroy',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categroy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categroy', to='core.categroy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categroy',
            name='slug',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(max_length=4),
        ),
    ]
